from pathlib import Path

with open(
    Path(__file__).parent.parent / f"src/I18n/font_msyh.hpp", "w", newline=""
) as wf, open(R"C:\Windows\Fonts\msyh.ttc", "rb") as f:
    wf.write("#pragma once\n")
    wf.write(f"// Autogenerated file from msyh.ttc\n")
    wf.write("static const unsigned char font_msyh[] = {\n\t")
    contents = f.read()
    print(len(contents))
    perline = 10
    for i, b in enumerate(contents):
        ending = " " if (i + 1) % perline != 0 else "\n\t"
        wf.write("0x{:02x}".format(b))
        if i != len(contents) - 1:
            wf.write("," + ending)
    wf.write("\n};")
    wf.close()
